### ISSUE TITLE
Incorrect classIsvalid check

### ISSUE THREAD

**Issue by TheHanna** [mariusc23/grunt-unclassify#1]
I'm not 100% sure this is an actual issue, I'm pretty new to Grunt overall, but I had to modify [line 222 of tasks/unclassify.js](https://github.com/mariusc23/grunt-unclassify/blob/master/tasks/unclassify.js#L222) from:

``` javascript
if (!classIsValid(elClass, classes) &&
```

to:

``` javascript
if (classIsValid(elClass, classes) &&
```

so it would return true and run on my HTML file. Here's my gruntfile:

``` javascript
module.exports = function(grunt) {
    grunt.initConfig({
        juice: {
            options: {},
            dist: {
                files: [{
                    src: 'index.html',
                    dest: 'build/index.html'
                }]
            }
        },
        unclassify: {
            options: {
                stylesheets: ['main.css'],
                overwrite: true
            },
            src: ['build/index.html']
        }
    });

    grunt.loadNpmTasks('grunt-juice');
    grunt.loadNpmTasks('grunt-unclassify');
    grunt.registerTask('default', ['juice', 'unclassify']);
};
```

Is this an issue, or am I using the plugin incorrectly?

**Comment by mariusc23** [comment]
Hi Brian,

That `if` statement checks to see if the class is not defined in the CSS (`!classIsValid`). If it is not defined, then the class gets added to the `removeClasses` array.

If you change it to `classIsValid`, it will remove classes that are defined in the CSS and leave undefined classes intact.

Your configuration looks correct. What does the plugin print in your terminal when you run grunt?

It would also help me debug if you can provide sample html & css that the plugin does not work with.

**Comment by TheHanna** [comment]
So I must have been super tired when I read the docs. The stylesheet I was feeding into the options had all of my styles in it, so _of course_ it wasn't removing them. This can be closed, I have the dumb.
